name: "Godot 4 Android Build"

on:
  push:
    branches:
      - "*"  # This triggers the build on every branch

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Android Keystore
        run: |
          mkdir -p /root/.android
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore /root/.android/debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.3.stable ~/.local/share/godot/export_templates/4.3.stable

      - name: Godot Android Export
        run: |
          cd src
          mkdir -p build/android
          godot --headless --editor --quit && godot --headless --export-release "Android" build/android/game.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: Android-APK
          path: src/build/android/game.apk
